{% set name = "skrub" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/skrub-{{ version }}.tar.gz
  sha256: 06d0d58cd7ce9f655d132ed27630ebce9c77752f93a1bf26dec4a92ec985d1cf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.10
    - scikit-learn >=1.2.1
    - numpy >=1.23.5
    - scipy >=1.9.3
    - pandas >=1.5.3
    - packaging >=23.1

test:
  imports:
    - skrub
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/skrub-data/skrub
  summary: Prepping tables for machine learning
  dev_url: https://github.com/skrub-data/skrub
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jeromedockes
    - Vincent-Maladiere
