{% set name = "skrub" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/skrub-{{ version }}.tar.gz
  sha256: 0573f1c12b5bfc609f28adecf091893ab4f09d6bbb94a3db20058c7572568e77

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - scikit-learn >=1.2.1
    - numpy >=1.23.5
    - scipy >=1.9.3
    - pandas >=1.5.3
    - jinja2 >=3.1.2
    - matplotlib-base >=3.4.3
    - requests >=2.25.0
    - pydot

test:
  imports:
    - skrub
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/skrub-data/skrub
  summary: Machine learning for dataframes
  dev_url: https://github.com/skrub-data/skrub
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jeromedockes
    - Vincent-Maladiere
    - glemaitre
    - rcap107
