{% set name = "skrub" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/skrub-{{ version }}.tar.gz
  sha256: ef12c46b69918ec596052586ebf83c041bd0b9d900b2c5a5bd241c00db38249e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.9
    - scikit-learn >=1.2.1
    - numpy >=1.23.5
    - scipy >=1.9.3
    - pandas >=1.5.3
    - packaging >=23.1
    - jinja2 >=3.1.2
    - matplotlib-base >=3.4.3

test:
  imports:
    - skrub
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/skrub-data/skrub
  summary: Prepping tables for machine learning
  dev_url: https://github.com/skrub-data/skrub
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jeromedockes
    - Vincent-Maladiere
    - glemaitre
